name: web_gpt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy>=1.21.0
  - matplotlib>=3.4.0
  - requests>=2.25.0
  - lxml>=4.6.0
  - html5lib>=1.1
  - urllib3>=1.26.0
  - pip:
    - selenium>=4.0.0
    - beautifulsoup4>=4.9.0
    - nltk>=3.6.0
    - wordcloud>=1.8.0